#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link      http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license   http://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';

/**
 * .env Project support
 */
(\Dotenv\Dotenv::createImmutable(__DIR__))->load();

/**
 * Yii Development Environment otherwise Production Environment
 */
if(getenv('APP_ENV') == 'dev') {
    define('YII_DEBUG', true);
    define('YII_ENV', 'dev');
}

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
